//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class sEnergyPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sEnergyPoint()
        {
            this.InvoiceSummaries = new HashSet<sInvoiceSummary>();
        }
    
        public int EnergyPointId { get; set; }
        public string EnergyPointNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sInvoiceSummary> InvoiceSummaries { get; set; }
    }
}
