//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class sGroup
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> Contact_ContactId { get; set; }
    }
}
