//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class sNetworkCharge
    {
        public int NetworkChargeId { get; set; }
        public decimal VariableBD { get; set; }
        public decimal VariableNBD { get; set; }
        public decimal CapacityCharge { get; set; }
        public decimal DemandCharge { get; set; }
        public decimal FixedCharge { get; set; }
    
        public virtual sInvoiceSummary InvoiceSummary { get; set; }
    }
}
