//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class sSite
    {
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public decimal SiteArea { get; set; }
    
        public virtual sCustomer Customer { get; set; }
        public virtual sGroup Group { get; set; }
    }
}
