//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyPoint
    {
        public int EnergyPointId { get; set; }
        public string ConnectionNumber { get; set; }
        public int SiteId { get; set; }
        public int SupplierId { get; set; }
        public string LocationNotes { get; set; }
        public int LinesCompanyId { get; set; }
        public string MeterId { get; set; }
        public int MeteringCompanyId { get; set; }
        public bool Enabled { get; set; }
        public int Phases { get; set; }
        public string GridExitPoint { get; set; }
        public string GridExitPointRegion { get; set; }
        public string ConnectionType { get; set; }
        public string GLCode { get; set; }
        public Nullable<int> AssessedCapacity { get; set; }
        public Nullable<int> WeatherStationId { get; set; }
        public string NIWAStationTemperature { get; set; }
        public string NIWAStationRain { get; set; }
        public string NIWAStationSun { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual EnergySupplier EnergySupplier { get; set; }
    }
}
