//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.EnergyPoints1 = new HashSet<EnergyPoint>();
        }
    
        public int SiteId { get; set; }
        public string SiteLogo { get; set; }
        public string SiteName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public int CustomerId { get; set; }
        public int GroupId { get; set; }
        public int EnergyPoints { get; set; }
        public bool Enabled { get; set; }
        public string InvoiceApproverName { get; set; }
        public string InvoiceApproverEmail { get; set; }
        public string InvoicePayerName { get; set; }
        public string InvoicePayerEmail { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> LandSqMeters { get; set; }
        public Nullable<int> TotalFloorSpaceSqMeters { get; set; }
        public Nullable<int> ProductiveFloorSpaceSqMeters { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyPoint> EnergyPoints1 { get; set; }
        public virtual Group Group { get; set; }
    }
}
