//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyCharge
    {
        public int EnergyChargeId { get; set; }
        public decimal BD0004 { get; set; }
        public decimal BD0408 { get; set; }
        public decimal BD0812 { get; set; }
        public decimal BD1216 { get; set; }
        public decimal BD1620 { get; set; }
        public decimal BD2024 { get; set; }
        public decimal NBD0004 { get; set; }
        public decimal NBD0408 { get; set; }
        public decimal NBD0812 { get; set; }
        public decimal NBD1216 { get; set; }
        public decimal NBD1620 { get; set; }
        public decimal NBD2024 { get; set; }
        public decimal BD0004R { get; set; }
        public decimal BD0408R { get; set; }
        public decimal BD0812R { get; set; }
        public decimal BD1216R { get; set; }
        public decimal BD1620R { get; set; }
        public decimal BD2024R { get; set; }
        public decimal NBD0004R { get; set; }
        public decimal NBD0408R { get; set; }
        public decimal NBD0812R { get; set; }
        public decimal NBD1216R { get; set; }
        public decimal NBD1620R { get; set; }
        public decimal NBD2024R { get; set; }
        public decimal BDQ0004 { get; set; }
        public decimal BDL0004 { get; set; }
    
        public virtual InvoiceSummary InvoiceSummary { get; set; }
    }
}
