//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherCharge
    {
        public int OtherChargeId { get; set; }
        public decimal BDSVC { get; set; }
        public decimal BDSVCR { get; set; }
        public decimal NBDSVC { get; set; }
        public decimal NBDSVCR { get; set; }
        public decimal EALevy { get; set; }
        public decimal EALevyR { get; set; }
        public decimal AdminCharge { get; set; }
    
        public virtual InvoiceSummary InvoiceSummary { get; set; }
    }
}
