//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataUpload.DataTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.InvoiceSummaries = new HashSet<InvoiceSummary>();
        }
    
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public decimal SiteArea { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceSummary> InvoiceSummaries { get; set; }
    }
}
